export {default as RegisterScreen} from "./Register"
export {default as LoginScreen} from "./Login"
export {default as ForgotScreen} from "./Forgot"
export {default as AdmScreen} from "./Adm"
export {default as IndexScreen} from "./Index"
export {default as PerfilScreen} from "./Perfil"